Training a simple linear model

In [1]:
import pip

In [2]:
#pip.main(['install','tensorflow'])

In [3]:
import tensorflow as tf

C:\Users\Administrator\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
#Variables
#first run
#W = tf.Variable([.3],tf.float32)
#b=tf.Variable([-.3],tf.float32)
#second run
W = tf.Variable([-1.0],tf.float32)
b=tf.Variable([1.0],tf.float32)

In [5]:
#placeholders
x=tf.placeholder(tf.float32)
#labela
y=tf.placeholder(tf.float32)

In [6]:
#linear model
linear_model = W*x+b

In [7]:
#loss
squared=tf.square(linear_model-y)
loss=tf.reduce_sum(squared)

In [8]:
init=tf.global_variables_initializer()

In [9]:
sess=tf.Session()
sess.run(init)

In [10]:
print(sess.run(loss,{x:[1,2,3,4],y:[0,-1,-2,-3]}))

0.0


In [11]:
sess.close()

#goback after first iteration to manually change the value of W and b
#move after the second iteration to automate

In [12]:
W = tf.Variable([.3],tf.float32)
b=tf.Variable([-.3],tf.float32)
#placeholders
x=tf.placeholder(tf.float32)
#labela
y=tf.placeholder(tf.float32)
#linear model
linear_model = W*x+b
#loss
squared=tf.square(linear_model-y)
loss=tf.reduce_sum(squared)

In [13]:
#select an optimize loss (alpha: learning rate)
optimizer = tf.train.GradientDescentOptimizer(0.001)

In [14]:
#minimize loss
train=optimizer.minimize(loss)

In [15]:
init=tf.global_variables_initializer()
sess = tf.Session()

In [16]:
sess.run(init)

In [17]:
for i in range(1000):
    sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})
    #print(i)

In [18]:
print(sess.run([W,b]))

[array([-0.8397583], dtype=float32), array([0.5288696], dtype=float32)]


In [19]:
sess.close()

demo code to explain the basic variables, constants and placeholders

In [20]:
state=tf.Variable(0)

In [21]:
one=tf.constant(1)

In [22]:
new_value=tf.add(state,one)

In [23]:
print(new_value) #it won't show the addition, for that you have to run it in a session

Tensor("Add_2:0", shape=(), dtype=int32)


In [24]:
update=tf.assign(state, new_value)

In [25]:
init_op=tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


Above we have created a graph and this session code executes a graph

In [26]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(3):
        session.run(update)
        print(session.run(state))

0
1
2
3


In [27]:
a=tf.placeholder(tf.float32)
print(a)

Tensor("Placeholder_4:0", dtype=float32)


In [28]:
b=a*2

In [29]:
with tf.Session() as sess:
    result=sess.run(b,feed_dict={a:3.5}) # as we haven't given any value to a therefore, we are giving a value here
    print(result)

7.0


In [30]:
dictionary={a:[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],b:[[13,14,15],[16,17,18],[19,20,21]]}
with tf.Session() as sess:
    result=sess.run(b,feed_dict=dictionary)
    print(result)

[[13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]]


Creating a graph

In [31]:
import tensorflow as tf

In [32]:
graph=tf.get_default_graph()

In [33]:
graph.get_operations()

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'Square' type=Square>,
 <tf.Operation 'Rank' type=Rank>,
 <tf.Operation 'range/start' type=Const>,
 <tf.Operation 'range/delta' type=Const>,
 <tf.Operation 'range' type=Range>,
 <tf.Operation 'Sum' type=Sum>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf.Ope

In [34]:
a=tf.constant(10, name="a")

In [35]:
b=tf.constant(20, name="b")

In [36]:
c=tf.add(a,b, name="c")

In [37]:
d=tf.multiply(a,b, name="d")

In [38]:
e=tf.multiply(c,d, name="e")

In [39]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'Square' type=Square>,
 <tf.Operation 'Rank' type=Rank>,
 <tf.Operation 'range/start' type=Const>,
 <tf.Operation 'range/delta' type=Const>,
 <tf.Operation 'range' type=Range>,
 <tf.Operation 'Sum' type=Sum>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf.Ope

In [40]:
operations[0].node_def

name: "Variable/initial_value"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
        dim {
          size: 1
        }
      }
      float_val: -1.0
    }
  }
}

In [41]:
sess=tf.Session()

In [42]:
print(sess.run(e))

6000


In [43]:
sess.close() # as we are not using with we give close(), otherwise not require.

Solve:
y=4(a^2)+5(b^2)+35 ;
a=-5
b=3